using System.IO;
using System.Linq;
using System.Text;
using com.convalise.UnityMaterialSymbols;
using UnityEditor;

namespace mdu.editor.ui
{
    [InitializeOnLoad]
    public class MaterialSymbolIconGenerator
    {
        public static readonly MaterialSymbolData X = new MaterialSymbolData('\u1234', false);
        private const string OUTOUT_PATH = "Assets/Runtime/Rendering/MaterialSymbolCode.cs";

        static MaterialSymbolIconGenerator()
        {
            EditorApplication.delayCall += initialized;   
        }

        private static void initialized()
        {
            EditorApplication.delayCall -= initialized;

            GenerateMaterialSymbolConstants();
        }

        private static void GenerateMaterialSymbolConstants()
        {
            var fontRef = MaterialSymbol.LoadFontRef();

            if((fontRef == null) || string.IsNullOrEmpty(fontRef.GetCodepointsEditorPath()))
                return;

            var codepoints = File.ReadAllLines(fontRef.GetCodepointsEditorPath())
                .Select((codepoint, index) => new MaterialSymbolSelectionWindow.CodepointData(codepoint, index))
                .GroupBy(cp => cp.name)
                .Select(gp => gp.First())
                .ToArray();


            var sb = new StringBuilder();
            sb.AppendLine("// This file is auto-generated by MaterialSymbolIconGenerator.cs. Do not edit manually.");
            sb.AppendLine("using com.convalise.UnityMaterialSymbols;");
            sb.AppendLine();
            sb.AppendLine("namespace mdu.ui");
            sb.AppendLine("{");
            sb.AppendLine("    public static class MaterialSymbolIcon");
            sb.AppendLine("    {");

            foreach (var cp in codepoints)
            {
                var name = cp.name.ToUpper();
                var code = cp.hex;
                
                // Generate the const field for the regular (outlined) icon.
                sb.AppendLine($"        /// <summary>Material Symbol: {name}</summary>");
                sb.AppendLine($"        public static readonly MaterialSymbolData ICON_{name} = new MaterialSymbolData(\'\\u{code}\', false);");
                // Generate the const field for the filled icon.
                sb.AppendLine($"        /// <summary>Material Symbol (Filled): {name}</summary>");
                sb.AppendLine($"        public static readonly MaterialSymbolData ICON_{name}_FILLED = new MaterialSymbolData(\'\\u{code}\', true);");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // Write the generated class to the output file.
            File.WriteAllText(OUTOUT_PATH, sb.ToString());
            
            // Refresh the asset database to make Unity aware of the new/changed script.
            AssetDatabase.Refresh();
        }
    }
}